import {
  Topic,
  TopicQuestion,
  SkillNode,
  Quest,
  WorldRegion,
} from '../../types';

export const DEFAULT_TOPICS: Topic[] = [
  {
    id: 'programming',
    name: 'Programming',
    slug: 'programming',
    icon: '💻',
    description: 'Code, apps, web development, and interactive software.',
    category: 'tech',
  },
  {
    id: 'drawing',
    name: 'Drawing & Art',
    slug: 'drawing',
    icon: '🎨',
    description: 'Digital illustration, gesture drawing, and character art.',
    category: 'art',
  },
  {
    id: 'photography',
    name: 'Photography',
    slug: 'photography',
    icon: '📸',
    description: 'Composition, exposure triangle, and visual storytelling.',
    category: 'photo',
  },
  {
    id: 'english',
    name: 'English Fluency',
    slug: 'english',
    icon: '🇬🇧',
    description: 'Conversational fluency, spoken dialogue, and idioms.',
    category: 'language',
  },
  {
    id: 'music',
    name: 'Music & Instrument',
    slug: 'music',
    icon: '🎵',
    description: 'Rhythm, ear training, pentatonic scales, and songs.',
    category: 'music',
  },
  {
    id: 'cooking',
    name: 'Culinary & Cooking',
    slug: 'cooking',
    icon: '🍳',
    description: 'Knife skills, heat control, and flavor balancing.',
    category: 'culinary',
  },
  {
    id: 'chess',
    name: 'Chess Strategy',
    slug: 'chess',
    icon: '♟️',
    description: 'Tactical puzzles, positional analysis, and endgames.',
    category: 'tactics',
  },
  {
    id: 'science',
    name: 'Science & Cosmos',
    slug: 'science',
    icon: '🔬',
    description: 'Empirical curiosity, physics, cosmos, and natural phenomena.',
    category: 'science',
  },
];

export const DEFAULT_TOPIC_QUESTIONS: Record<string, TopicQuestion[]> = {
  programming: [
    {
      id: 'prog_goal',
      topicSlug: 'programming',
      question: 'What do you want to accomplish in Programming?',
      subtitle: 'Your personal north star for writing code.',
      type: 'text',
      placeholder: 'e.g. Learn JavaScript well enough to build my own apps and interactive tools.',
      required: true,
    },
    {
      id: 'prog_focus',
      topicSlug: 'programming',
      question: 'What would you love to build most?',
      subtitle: 'Customizes your coding challenges and mini-projects.',
      type: 'single_choice',
      options: ['Websites & Web Apps', 'Automations & Scripts', 'Interactive Visuals & Games', 'Core Computer Science & Logic'],
      required: true,
    },
    {
      id: 'prog_level',
      topicSlug: 'programming',
      question: 'What is your current familiarity with code?',
      subtitle: 'We calibrate step complexity accordingly.',
      type: 'single_choice',
      options: ['Absolute beginner (first time)', 'Know basics (variables, loops)', 'Built small scripts or projects', 'Experienced in another language'],
      required: true,
    },
    {
      id: 'prog_style',
      topicSlug: 'programming',
      question: 'How do you prefer learning programming?',
      subtitle: 'Shape your daily practice experience.',
      type: 'single_choice',
      options: ['Building real projects', 'Coding challenges & puzzles', 'Visual games', 'Short concept breakdowns'],
      required: true,
    },
  ],
  drawing: [
    {
      id: 'draw_goal',
      topicSlug: 'drawing',
      question: 'What is your primary drawing goal?',
      subtitle: 'The vision you want to bring to life on paper or screen.',
      type: 'text',
      placeholder: 'e.g. Draw expressive characters and scenes without stiff reference tracing.',
      required: true,
    },
    {
      id: 'draw_medium',
      topicSlug: 'drawing',
      question: 'What visual medium excites you most?',
      subtitle: 'Customizes your sketchbook and digital art prompts.',
      type: 'single_choice',
      options: ['Digital illustration & iPad', 'Traditional pencil & sketchbook', 'Anime & Character design', 'Urban sketching & landscapes'],
      required: true,
    },
    {
      id: 'draw_exp',
      topicSlug: 'drawing',
      question: 'What is your current drawing experience?',
      subtitle: 'Helps us suggest the right gesture and shape exercises.',
      type: 'single_choice',
      options: ['Starting from stick figures', 'Know basic shapes and lines', 'Draw occasionally', 'Experienced artist looking for consistency'],
      required: true,
    },
    {
      id: 'draw_struggle',
      topicSlug: 'drawing',
      question: 'What feels most challenging right now?',
      subtitle: 'We target this area gently with micro-quests.',
      type: 'single_choice',
      options: ['Stiff lines & shaky hand control', 'Proportions & 3D perspective', 'Color choices & shading', 'Finishing pieces'],
      required: true,
    },
  ],
  photography: [
    {
      id: 'photo_goal',
      topicSlug: 'photography',
      question: 'What kind of moments do you want to capture?',
      subtitle: 'Your artistic photographic viewpoint.',
      type: 'text',
      placeholder: 'e.g. Take cinematic street and travel photos with beautiful natural light.',
      required: true,
    },
    {
      id: 'photo_gear',
      topicSlug: 'photography',
      question: 'What gear do you primarily use?',
      subtitle: 'Quests adapt to your camera interface.',
      type: 'single_choice',
      options: ['Smartphone camera', 'Mirrorless / DSLR', 'Vintage Film camera', 'Action / Drone'],
      required: true,
    },
    {
      id: 'photo_genre',
      topicSlug: 'photography',
      question: 'What subjects inspire you most?',
      subtitle: 'Determines your field observation challenges.',
      type: 'single_choice',
      options: ['Street & Candid Life', 'Portraits & People', 'Nature & Landscapes', 'Architecture & Geometry'],
      required: true,
    },
    {
      id: 'photo_focus',
      topicSlug: 'photography',
      question: 'What would you like to master first?',
      subtitle: 'Your initial skill focus.',
      type: 'single_choice',
      options: ['Composition & Rule of Thirds', 'Lighting & Shadow contrast', 'Storytelling in a single shot', 'Color grading & Editing'],
      required: true,
    },
  ],
  english: [
    {
      id: 'eng_goal',
      topicSlug: 'english',
      question: 'What is your main fluency goal?',
      subtitle: 'The speaking milestone you want to reach.',
      type: 'text',
      placeholder: 'e.g. Speak smoothly in everyday conversations without freezing or searching for words.',
      required: true,
    },
    {
      id: 'eng_context',
      topicSlug: 'english',
      question: 'Where do you most want to use English?',
      subtitle: 'Focuses your interactive dialogue simulations.',
      type: 'single_choice',
      options: ['Casual daily social chats', 'Travel & Ordering food abroad', 'Work meetings & Professional presentation', 'Consuming media without subtitles'],
      required: true,
    },
    {
      id: 'eng_confidence',
      topicSlug: 'english',
      question: 'How does your speaking feel today?',
      subtitle: 'Helps us tailor speaking vs listening pace.',
      type: 'single_choice',
      options: ['Hesitant to speak aloud', 'Understand well but struggle to reply quickly', 'Conversational with grammar slips', 'Comfortable but want natural idioms'],
      required: true,
    },
    {
      id: 'eng_style',
      topicSlug: 'english',
      question: 'How do you enjoy practicing languages?',
      subtitle: 'Customizes your interactive audio workbench.',
      type: 'single_choice',
      options: ['Spoken dialogue simulations', 'Short audio listening challenges', 'Real-life scenario vocabulary', 'Pronunciation & shadow repetition'],
      required: true,
    },
  ],
  music: [
    {
      id: 'music_goal',
      topicSlug: 'music',
      question: 'What is your musical dream?',
      subtitle: 'The songs or sounds you want to play.',
      type: 'text',
      placeholder: 'e.g. Play my favorite songs smoothly by ear and understand basic chord progressions.',
      required: true,
    },
    {
      id: 'music_instrument',
      topicSlug: 'music',
      question: 'What instrument are you learning?',
      subtitle: 'Guides technical exercises and notation.',
      type: 'single_choice',
      options: ['Piano / Keyboard', 'Acoustic / Electric Guitar', 'Singing & Voice', 'Music Production & Beats'],
      required: true,
    },
    {
      id: 'music_exp',
      topicSlug: 'music',
      question: 'What is your current background in music?',
      subtitle: 'Calibrates ear training and exercises.',
      type: 'single_choice',
      options: ['Complete beginner (never played)', 'Know a few open chords or keys', 'Played in childhood', 'Intermediate player returning to basics'],
      required: true,
    },
    {
      id: 'music_priority',
      topicSlug: 'music',
      question: 'What skill would you love to develop first?',
      subtitle: 'Your immediate learning track.',
      type: 'single_choice',
      options: ['Rhythm & Groove timing', 'Ear training & recognizing melodies', 'Learning whole songs', 'Music theory made simple'],
      required: true,
    },
  ],
  cooking: [
    {
      id: 'cook_goal',
      topicSlug: 'cooking',
      question: 'What do you want to accomplish in the kitchen?',
      subtitle: 'Your culinary aspiration.',
      type: 'text',
      placeholder: 'e.g. Cook delicious, healthy weeknight dinners with confidence and great knife skills.',
      required: true,
    },
    {
      id: 'cook_style',
      topicSlug: 'cooking',
      question: 'What type of food inspires you most?',
      subtitle: 'Shapes your recipe experiments and technique quests.',
      type: 'single_choice',
      options: ['Quick wholesome weeknight meals', 'Comfort food & Baking', 'Global street food & Spices', 'Classic restaurant techniques'],
      required: true,
    },
    {
      id: 'cook_confidence',
      topicSlug: 'cooking',
      question: 'How comfortable are you right now?',
      subtitle: 'Helps us match ingredient and knife technique levels.',
      type: 'single_choice',
      options: ['Total beginner (can make eggs and toast)', 'Know basic cooking but follow recipes strictly', 'Cook regularly and want more flavor intuition', 'Confident cook exploring new cuisines'],
      required: true,
    },
    {
      id: 'cook_focus',
      topicSlug: 'cooking',
      question: 'What is one culinary skill you want to master?',
      subtitle: 'Focus for your hands-on quests.',
      type: 'single_choice',
      options: ['Safe knife skills & speed', 'Flavor balancing (acid, salt, fat, heat)', 'Sauces & Marinades', 'Pan searing & heat control'],
      required: true,
    },
  ],
  chess: [
    {
      id: 'chess_goal',
      topicSlug: 'chess',
      question: 'What is your chess aspiration?',
      subtitle: 'Your rating or strategic milestone.',
      type: 'text',
      placeholder: 'e.g. Reach 1200 rating and spot tactical forks before making moves.',
      required: true,
    },
    {
      id: 'chess_rating',
      topicSlug: 'chess',
      question: 'What is your current chess level?',
      subtitle: 'Calibrates interactive chessboard puzzles.',
      type: 'single_choice',
      options: ['Just learned how pieces move', 'Casual player (under 1000 ELO)', 'Club player (1000 - 1400 ELO)', 'Experienced (1400+ ELO)'],
      required: true,
    },
    {
      id: 'chess_weakness',
      topicSlug: 'chess',
      question: 'Where do you feel you lose most games?',
      subtitle: 'We will target this area with custom puzzles.',
      type: 'single_choice',
      options: ['Missing simple tactical forks & pins', 'Back-rank blunders & king safety', 'Middle-game planning when there are no captures', 'Endgame conversion with few pieces'],
      required: true,
    },
    {
      id: 'chess_style',
      topicSlug: 'chess',
      question: 'How do you prefer calculating?',
      subtitle: 'Shapes your tactical training curriculum.',
      type: 'single_choice',
      options: ['Interactive move-by-move puzzles', 'Positional master game analysis', 'Opening principles and ideas', 'Endgame drills'],
      required: true,
    },
  ],
  science: [
    {
      id: 'sci_goal',
      topicSlug: 'science',
      question: 'What scientific curiosity drives you?',
      subtitle: 'Your intellectual exploration frontier.',
      type: 'text',
      placeholder: 'e.g. Understand how the cosmos and quantum mechanics actually work.',
      required: true,
    },
    {
      id: 'sci_field',
      topicSlug: 'science',
      question: 'Which scientific domain excites you most?',
      subtitle: 'Shapes your conceptual deep-dive quests.',
      type: 'single_choice',
      options: ['Astrophysics & Space', 'Quantum Physics & Reality', 'Neuroscience & Human Mind', 'Evolution & Biological Systems'],
      required: true,
    },
    {
      id: 'sci_approach',
      topicSlug: 'science',
      question: 'How do you like scientific ideas explained?',
      subtitle: 'Sets the tone for your daily quest explanations.',
      type: 'single_choice',
      options: ['Visual analogies & Thought experiments', 'Empirical real-world evidence & History', 'Core mathematical models', 'Interactive simulations'],
      required: true,
    },
  ],
};

export function getGenericQuestionsForTopic(topic: Topic): TopicQuestion[] {
  return [
    {
      id: `${topic.slug}_goal`,
      topicSlug: topic.slug,
      question: `What is your primary goal in ${topic.name}?`,
      subtitle: `Your personal compass for ${topic.name}.`,
      type: 'text',
      placeholder: `e.g. Explore fundamentals of ${topic.name} and build small creative habits.`,
      required: true,
    },
    {
      id: `${topic.slug}_why`,
      topicSlug: topic.slug,
      question: `Why do you want to learn ${topic.name}?`,
      subtitle: 'What inspires you right now?',
      type: 'single_choice',
      options: ['Personal curiosity & enjoyment', 'Creative project', 'Career / Future skills', 'Mental fitness & challenge'],
      required: true,
    },
    {
      id: `${topic.slug}_level`,
      topicSlug: topic.slug,
      question: `What is your current level in ${topic.name}?`,
      subtitle: 'We calibrate challenge difficulty to your pace.',
      type: 'single_choice',
      options: ['Complete beginner', 'Know some basics', 'Intermediate', 'Advanced'],
      required: true,
    },
  ];
}

export function getCategoryIslandTheme(category: Topic['category']) {
  switch (category) {
    case 'tech':
      return {
        ground: '#10b981',
        primary: '#059669',
        accent: '#34d399',
        fog: '#ecfdf5',
        regionType: 'coding_lab',
        theme: 'tech',
      };
    case 'art':
      return {
        ground: '#f59e0b',
        primary: '#d97706',
        accent: '#fbbf24',
        fog: '#fffbeb',
        regionType: 'atelier_studio',
        theme: 'art',
      };
    case 'photo':
      return {
        ground: '#6366f1',
        primary: '#4f46e5',
        accent: '#818cf8',
        fog: '#eef2ff',
        regionType: 'darkroom_grove',
        theme: 'photo',
      };
    case 'language':
      return {
        ground: '#ec4899',
        primary: '#db2777',
        accent: '#f472b6',
        fog: '#fdf2f8',
        regionType: 'agora_terrace',
        theme: 'language',
      };
    case 'music':
      return {
        ground: '#8b5cf6',
        primary: '#7c3aed',
        accent: '#a78bfa',
        fog: '#f5f3ff',
        regionType: 'acoustic_hollow',
        theme: 'music',
      };
    case 'culinary':
      return {
        ground: '#ea580c',
        primary: '#c2410c',
        accent: '#fb923c',
        fog: '#fff7ed',
        regionType: 'hearth_kitchen',
        theme: 'culinary',
      };
    case 'tactics':
      return {
        ground: '#475569',
        primary: '#334155',
        accent: '#64748b',
        fog: '#f8fafc',
        regionType: 'citadel_keep',
        theme: 'tactics',
      };
    case 'science':
    default:
      return {
        ground: '#06b6d4',
        primary: '#0891b2',
        accent: '#22d3ee',
        fog: '#ecfeff',
        regionType: 'observatory_peak',
        theme: 'science',
      };
  }
}
